version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports: 
      - "3320:3306"
    volumes:
      - /home/ubuntu/covitmx/database5.7:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "adminsql.server"
    networks:
      - covidmx

  api:
    build:
      context: .
    container_name: api
    image: api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      HOST: db
      PORT: 3306
    depends_on:
      - db
    networks:
      - covidmx

  web:
    image: nginx
    container_name: web
    restart: always
    volumes:
      - ./../www:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - db
      - api
    networks: 
      - covidmx
    

networks:
  covidmx:
