# Generated by Django 3.1.1 on 2020-09-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha de actualizacion')),
                ('register_id', models.CharField(max_length=10, verbose_name='ID de registro')),
                ('origin', models.IntegerField(verbose_name='Origen')),
                ('sector', models.IntegerField(verbose_name='Sector')),
                ('entity_um', models.IntegerField(verbose_name='Entidad UM')),
                ('gender', models.IntegerField(verbose_name='Sexo')),
            ],
        ),
    ]
