# Generated by Django 3.1.1 on 2020-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='covid',
            new_name='covidModel',
        ),
    ]
