# Generated by Django 3.1.1 on 2020-09-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200909_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasPorEdad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(max_length=15, verbose_name='Rango de edad')),
                ('cantidad_casos', models.IntegerField(verbose_name='Cantidad de Casos')),
                ('porcentaje', models.IntegerField(verbose_name='Porcentaje de mortalidad')),
                ('m_diabetes', models.CharField(max_length=10, verbose_name='con Diabetes')),
                ('m_epoc', models.CharField(max_length=10, verbose_name='con EPOC')),
                ('m_asma', models.CharField(max_length=10, verbose_name='con Asma')),
                ('m_hipertension', models.CharField(max_length=10, verbose_name='con Hipertension')),
                ('m_obesidad', models.CharField(max_length=10, verbose_name='con Obesidad')),
                ('m_tabaquismo', models.CharField(max_length=10, verbose_name='con Tabaquismo')),
                ('muertes', models.IntegerField(verbose_name='Muertes')),
                ('recuperados', models.IntegerField(verbose_name='Recuperados')),
                ('sexo', models.CharField(max_length=20, verbose_name='Genero')),
            ],
        ),
    ]
